from pathlib import Path
from datetime import datetime,timezone
import sys,json,csv,html,re,subprocess,shutil
import numpy as np,rasterio,yaml,jsonschema
from PIL import Image,ImageDraw
from pyproj import Transformer
sys.path.insert(0,str(Path(__file__).resolve().parents[2]))
from forest_change.evidence import checksum,write_json
R=Path(__file__).resolve().parent;REPO=R.parents[1];LAB=Path('/Users/server/projects/forest-cover-lab');RUN=REPO/'runs/aoi-s2-s1-jja-2025-2026-sigma';now=datetime.now(timezone.utc).isoformat()
def load(name):return json.loads((R/name).read_text())
rois=load('rois.geojson');audit=load('raster_audit.json');exp=load('threshold_experiments.json');shared=load('common_support_and_roi_robust.json');pers=load('persistence_experiment.json');sem=load('semantic_trace.json');metrics=load('roi_metrics.json');verify=load('manifest_verification.json')
# Native analysis-grid RGB crops and locator. No spatial correction.
for roi in ('ROI-01','ROI-02'):
 for role in ('reference','target'):
  with rasterio.open(R/f'{roi}-{role}-georef.tif') as s:a=s.read(masked=True).filled(np.nan)
  rgb=np.moveaxis(np.uint8(np.clip(np.nan_to_num(a)/.3,0,1)**(1/2.2)*255),0,-1);Image.fromarray(rgb).save(R/f'{roi}-{role}-native.png')
loc=Image.open(R/'target.png').convert('RGB');draw=ImageDraw.Draw(loc);tr=Transformer.from_crs(4326,3857,always_xy=True);x0,y0=tr.transform(24.4,58.2);x1,y1=tr.transform(24.9,58.6)
for f in rois['features']:
 ring=f['geometry']['coordinates'][0];pts=[((tr.transform(*p)[0]-x0)/(x1-x0)*loc.width,(y1-tr.transform(*p)[1])/(y1-y0)*loc.height) for p in ring];draw.line(pts,fill='yellow',width=4);draw.text(pts[0],f['properties']['id'],fill='white')
loc.save(R/'roi_locator.png')
# All outputs inspected at overview scale; default experiment at full source-image scale.
folder=R/'experiments/k2.5_drop0.15_floor0.02'
for mode in ('optical','and','or'):
 p=folder/f'maps_{mode}';bg=Image.open(p/'target.png').convert('RGBA');ov=Image.open(p/'anomalies.png').convert('RGBA');Image.alpha_composite(bg,ov).save(R/f'robust-default-{mode}.png')
# Record actual source identity, evidence scope and access rather than treating all sources as full text.
sources=[
 {'id':'L01','authors':'Radoux et al.','year':2016,'title':"Sentinel-2’s Potential for Sub-Pixel Landscape Feature Detection",'doi':'10.3390/rs8060488','url':'https://www.mdpi.com/2072-4292/8/6/488','access':'indexed original abstract/discussion/conclusion excerpts; direct full-text fetch returned 429','section':'Abstract, Discussion, Conclusions','sensor':'pre-operational Sentinel-2; comparison with Landsat-8/SPOT-5','resolution':'10–20 m S2','geography':'study landscapes, not Estonia ROI','algorithm':'spectral separability and empirical point-spread-function framework','validation':'foreground/background separability experiments','finding':'Subpixel visibility depends on contrast and spatial response. Reported road limit is context-specific.','transferability':'Does not establish an NDVI anomaly cutoff or a universal road-width detection limit.','kg':['DS-0002','measurement:ndvi'],'inference':'Mixed-pixel dilution can explain optical/SAR disagreement; actual local width remains uncertain.'},
 {'id':'L02','authors':'Oehmcke, Thrysøe, Borgstad, Salles, Brandt, Gieseke','year':2019,'title':'Detecting Hardly Visible Roads in Low-Resolution Satellite Time Series Data','url':'https://arxiv.org/abs/1912.05026','access':'full original author paper text read','section':'II-A, III, IV and Appendix','sensor':'Sentinel-2 L2A','resolution':'10–60 m bands; 5/10 m label rasters','geography':'six European S2 tiles','temporal':'12 timestamps, 2016–2018','algorithm':'supervised U-Net variants, ordinal visibility classes, temporal model','validation':'OSM-derived train/test road labels','finding':'Visibility varies with road type/width; labels and temporal context influence extraction.','transferability':'OSM label noise/domain shift and supervised setup differ from this unsupervised gate.','kg':['DS-0002','observation:optical-vegetation-state']},
 {'id':'L03','authors':'Verbesselt, Hyndman, Newnham, Culvenor','year':2010,'title':'Detecting trend and seasonal changes in satellite image time series','doi':'10.1016/j.rse.2009.08.014','url':'https://otext.robjhyndman.com/publications/bfast1/','manuscript_url':'https://www.researchgate.net/profile/Jan-Verbesselt/publication/252964434_Abrupt_gradual_and_phenological_change_analysis_using_satellite_image_time_series/links/00b49523bfc21f3b0f000000/Abrupt-gradual-and-phenological-change-analysis-using-satellite-image-time-series.pdf','access':'author bibliographic page and original-author preprint methods/conclusion read','section':'Preprint 2, 5, 6','authenticity_limit':'Preprint footer contains an inconsistent submission year; journal identity checked against author bibliography.','sensor':'MODIS NDVI','temporal':'16-day composites, multi-year 2000–2008 application','geography':'southeastern Australia forest','algorithm':'iterative trend/seasonality decomposition and structural breaks','validation':'simulations and forest inventory context','finding':'Separates temporal components; change characterization still needs causal interpretation.','transferability':'Not executable defensibly with eight reference dates and three June targets; not a road detector.','kg':['method:temporal-persistence','observation:optical-vegetation-state']},
 {'id':'L04','authors':'Zhu and Woodcock','year':2014,'title':'Continuous change detection and classification of land cover using all available Landsat data','doi':'10.1016/j.rse.2014.01.011','url':'https://gerslab.cahnr.uconn.edu/wp-content/uploads/sites/2514/2021/06/ZheZhu_CCDC.pdf','access':'author-hosted journal full text read','section':'2, 3.1–3.3, printed pp.154–157','sensor':'Landsat TM/ETM+ surface reflectance','resolution':'Landsat spatial scale','geography':'coastal New England','temporal':'519 images, 1982–2011','preprocessing':'L1T registration, LEDAPS, Fmask and temporal screening','algorithm':'seasonal/trend regression, repeated residual deviations, classification','validation':'aerial/field-supported reference sites','finding':'Single-date ephemeral effects and clear-scene selection can undermine inference; uses repeated dates.','transferability':'Published temporal model and data requirements differ from the June persistence heuristic; thresholds not transferable.','kg':['method:temporal-persistence','measurement:persistence-count']},
 {'id':'L05','authors':'ESA-ESRIN','year':1996,'title':'Some Basic Radar Principles (SP-1199)','url':'https://www.esa.int/esapub/sp/sp1199/get21.htm','access':'official full text read','section':'backscatter factors and polarization/incidence paragraphs','sensor':'radar, general physical principles','algorithm':'physical explanation, no classifier','validation':'not a location-specific validation study','finding':'Moisture, roughness, polarization and incidence affect backscatter; a wet or rough surface need not exhibit a drop.','transferability':'Explains mechanisms, not actual local weather or SAR cause.','kg':['DS-0003','observation:sar-backscatter-state']},
 {'id':'L06','authors':'Element 84','year':2026,'title':'Earth Search documentation and offset issue #66','url':'https://github.com/Element84/earth-search/blob/main/README.md','related_url':'https://github.com/Element84/earth-search/issues/66','access':'provider repository documentation and issue body read','section':'collection/calibration documentation, issue body','sensor':'Sentinel-2 COG L2A','finding':'Collection metadata and offset behavior need product-specific checks; issue is a user report.','transferability':'Does not independently validate this run’s explicit gain=.0001, no-second-offset interpretation.','kg':['DS-0002','access:live-catalogue']},
 {'id':'L07','authors':'Planetary Computer issue reporter','year':2025,'title':'Sentinel-1 RTC — step changes in terrain correction/projection #404','url':'https://github.com/microsoft/PlanetaryComputer/issues/404','access':'original issue body read; user report, not provider-confirmed general defect','section':'description/reproduction','sensor':'Planetary Computer S1 RTC','geography':'Philippines example','finding':'Reported persistent geolocation shift in another region.','transferability':'Reason to check local registration, not evidence that this Estonia run has a shift. Optical checks do not certify S1 alignment.','kg':['DS-0003','validation:forest-evidence']},
 {'id':'L08','authors':'Rousseeuw and Croux','year':1993,'title':'Alternatives to the Median Absolute Deviation','doi':'10.1080/01621459.1993.10476408','url':'https://wis.kuleuven.be/stat/robust/papers/publications-1993/rousseeuwcroux-alternativestomedianad-jasa-1993.pdf','access':'original author-hosted indexed abstract excerpt; full-text open failed','section':'abstract','algorithm':'robust scale estimators','finding':'MAD with a normal-consistency multiplier is robust; small-sample behavior still matters.','transferability':'Does not validate the noise floors, minimum count, effect-size cutoff or false-positive control for NDVI.','kg':['method:ndvi-anomaly'],'semantic_gap':'robust screening method unregistered'},
 {'id':'L09','authors':'identity not fully verified','year':2024,'title':'Monitoring road development in Congo Basin forests with multi-sensor satellite imagery and deep learning','url':'https://www.sciencedirect.com/science/article/pii/S0034425724004061','access':'original publisher search abstract only; full text unavailable','sensor':'Sentinel-1 and Sentinel-2','geography':'Congo Basin','algorithm':'supervised multi-sensor deep learning','finding':'Road monitoring reported with an independently evaluated supervised model.','transferability':'Methods/labels not fully read; cannot justify exact thresholds or transfer accuracy to Estonia.','excluded_from_parameter_justification':True,'kg':['DS-0002','DS-0003']}
]
for s in sources:s.update({'retrieved_at':now,'inclusion':'mechanism or method-design context; no ROI ground truth'})
write_json(R/'literature_evidence.json',{'sources':sources,'search_date':'2026-10-06','queries':['Sentinel-2 forest roads narrow linear detection Sentinel-1 study','site.esa.int Sentinel 1 backscatter moisture roughness vegetation radar roads','Verbesselt 2010 BFAST Zhu Woodcock 2014 continuous change detection classification full text','Sentinel-2’s Potential for Sub-Pixel Landscape Feature Detection 8 488 DOI','Rousseeuw Croux 1993 Alternatives median absolute deviation 1.4826 doi original paper','site.planetarycomputer.microsoft.com dataset sentinel-1-rtc radiometric terrain correction'],'limits':'Indexed excerpts, abstracts and issue reports are explicitly weaker than original methods read. No literature proves ROI identity.'})
review='''# Literature and threshold interpretation

Optical visibility and a radar decrease are different requirements. A narrow bright surface or cleared verge can alter optical reflectance while occupying only part of a 20 m analysis pixel. Radoux’s separability framework and Oehmcke’s road models support width/contrast-dependent visibility, but do not validate this NDVI/SAR gate [L01, L02]. Apparent sampled widths are only visual estimates, and archived optical source windows are already resampled from nominal 10 m bands to 20 m. No universal minimum detectable width is claimed.

ESA explains how moisture, surface roughness, polarization and incidence influence radar returns [L05]. Maintained/increased backscatter after clearing is therefore a plausible alternative to a VV/VH drop. The actual local moisture state was not measured. The radar summer median and one June optical image describe different temporal summaries. Scene-level RTC compatibility and common orbit do not establish exact local co-registration; the issue report L07 is a caution from another location, not a diagnosed defect here.

CCDC explicitly treats geometric registration and atmosphere as prerequisites, combines temporal screening with repeated observations, and documents loss of useful clear pixels when selecting only clear scenes [L04, Methods]. This supports checking clear-scene sampling bias; it does not calibrate our eight-date reference. BFAST separates trend and seasonality using a longer series [L03, Methods]. Neither framework was run on this inadequate series. The three-date experiment is a separate heuristic, not either published algorithm or the Lab’s consecutive-month forest-confirmation method.

The supplied MAD helper was executed for all 18 declared combinations. Median/MAD reduces the influence of some reference outliers, while the minimum drop avoids flagging arbitrarily tiny effects when variability is near zero. The normal-consistency multiplier in L08 is not evidence of a normal NDVI error distribution. Five reference dates, epsilon={.02,.05}, effect sizes {.1,.15,.2} and k={2,2.5,3} remain unvalidated experimental choices. Without held-out independent road labels, smaller areas and more persistence are stability diagnostics, not precision/recall, significance, probability or false-discovery control. All settings were retained; none was selected for looking most like a road.

Paired-valid AND, OR and disagreement were generated using the repository fusion functions. AND is restrictive by construction; OR admits signals from either sensor and can increase false positives as well as recall. No probabilistic fusion was fitted because independent labels and calibration/holdout design are absent. The Congo abstract [L09] points to a different supervised workflow; it cannot justify transferring its results.

'''
for s in sources:review+=f"- [{s['id']}: {s['title']}]({s['url']}) ({s['year']}): {s['access']}. {s.get('section','')} {s['finding']} {s['transferability']}\n"
(R/'literature_review.md').write_text(review)
bib=''
for s in sources:
 fields={'title':s['title'],'author':s['authors'],'year':str(s['year']),'url':s['url']}
 if 'doi' in s:fields['doi']=s['doi']
 bib+='@misc{'+s['id']+',\n'+',\n'.join('  '+k+' = {'+v+'}' for k,v in fields.items())+'\n}\n\n'
(R/'references.bib').write_text(bib)
# Orthophoto ledger distinguishes layer year from conflicting metadata and from adequate coverage.
ind=load('independent_map_evidence.json');ind['records']=[r for r in ind['records'] if 'query' in r]
for r in ind['records']:
 r['observation_date']=None;r['native_resolution']='unverified for returned layer; metainfo says OF_GSD=25 but dates do not match layer attribution';r['metadata_date']='2023-06-09';r['access_mode']='derived-WMS-window';r['date_conflict']='2025 imagery layer versus generic metainfo latest-flight 09.06.2023; not resolved'
 r['assessment']={k:'inconclusive' for k in ('new_construction','appearance_interval','prior_forest','legal_attribution')}
 if r['layer_year']==2025 and r.get('nontransparent_fraction',0)>.01:
  r['assessment']['physical_road_existence']='supports at sampled ROI-02 point; paved road/vehicles visible' if r['roi_id']=='ROI-02' else 'inconclusive; clearing and forest tracks visible, not an established road identity'
 else:r['assessment']['physical_road_existence']='unavailable; no imagery coverage, attribution pixels only'
# Keep failed 2023 queries and response files in evidence, without giving attribution pixels a coverage label.
for roi in ('ROI-01','ROI-02'):
 p=R/f'cache/orthophotos/{roi}-2023.png'
 if p.exists():ind['records'].append({'id':roi+'-2023','roi_id':roi,'layer_year':2023,'path':str(p.relative_to(R)),'sha256':checksum(p),'accessibility':'no imagery coverage','observation_date':None,'assessment':{'all_claims':'unavailable'},'source_independence_group':'national-aerial-imagery','limitations':['Only attribution text, not ground imagery.']})
ind['records'].append({'id':'C01','url':'https://www.rbestonia.ee/rail-baltica-ehitus-edeneb-parnumaal-tori-vallas-mis-saab-aastaks-2030-taas-rongiuhenduse/','original_publication_date':'2025-11-25','observation_date':None,'source_independence_group':'Rail-Baltic-project-reports','accessibility':'official text read','assessment':{'road_identity':'inconclusive','new_construction':'inconclusive'},'context':'Describes rail corridor work and access roads in Tori/Pärnu; location-specific matching not established.','limitations':['Project-promoter report, originally sponsored content; regional context rather than independent surveyed geometry.']})
ind['records'].append({'id':'C02','url':'https://www.rbestonia.ee/rail-baltica-ehitus-parnumaal-hoogustub/','publication_date':'2025-03-03','original_publication_date':'2025-02-22','observation_date':None,'source_independence_group':'Rail-Baltic-project-reports','accessibility':'official text read','assessment':{'road_identity':'inconclusive'},'context':'Regional mainline, access and terminal works. Railway earthworks are an alternative to a completed road.','limitations':['No exact sampled-road construction date or alignment proved.']})
write_json(R/'independent_map_evidence.json',ind);write_json(R/'independent_evidence_ledger.json',ind)
cor='''# Independent corroboration

Jurisdiction: Estonia (AOI 24.4–24.9° E, 58.2–58.6° N). Public official historical WMS capabilities were fetched and inspected. Two 500 m windows were requested at 0.5 m display sampling, with PNG responses and georeferenced RGBA GeoTIFF derivatives cached under cache/orthophotos/. WMS render sampling is not native source resolution. No full scene was downloaded.

2023 and 2024 imagery layers had no ground-image coverage at these points; small nontransparent attribution text must not count as coverage. The 2025 layer had complete imagery. Generic metainfo returned flight date 9 June 2023 and GSD=25, inconsistent with the chosen year layer. Those responses are preserved, but neither the date nor native resolution is assigned to the returned pixels. Exact source sheet listings could not be accessed through the web tool. No adequately dated independent before/after pair or verified 2026 high-resolution image was obtained; no construction interval can be bounded.

ROI-02’s sampled 2025-layer aerial image shows a paved road with vehicles. The original 15 June 2025 Sentinel RGB also shows a road-like alignment. This supports physical existence and contradicts describing the sampled main carriageway as entirely absent at the optical reference date, while widening and surrounding clearing remain unresolved. ROI-01’s aerial window shows existing forestry clearings/tracks; a highway identity and all-new corridor cannot be inferred. The entire manually sampled corridor is not established by one aerial window.

Rail Baltic Estonia’s 2025 reports describe railway and access-road construction in the region. They introduce a railway/earthworks alternative but do not geospatially identify these ROIs. No permits, official completed-road alignment, forestry authorisation, legal forest baseline or field survey was obtained. Project reports are not treated as independent aerial observations. OSM was not used as evidence of absence or construction timing.

Each proposition/source assessment and date conflict is in independent_map_evidence.json. Remaining evidence: exact surveyed corridor, dated native-resolution source sheets before and after, current rail/road alignment, construction records, and a separately approved prior-forest baseline.\n'''
(R/'corroboration.md').write_text(cor);(R/'corroboration_report.md').write_text(cor)
# Source-grounded proposals using current corpus schema. No canonical graph writes.
K=R/'knowledge_candidates';K.mkdir(exist_ok=True);schema=json.loads((LAB/'graph/schemas/concept.schema.json').read_text());index=[]
proposals=[('method:robust-ndvi-screening','method','Experimental robust NDVI screening','knowledge/methods/method-robust-ndvi-screening.md',['https://doi.org/10.1080/01621459.1993.10476408','https://gerslab.cahnr.uconn.edu/wp-content/uploads/sites/2514/2021/06/ZheZhu_CCDC.pdf'],[{'type':'REQUIRES_OBSERVATION','target':'observation:optical-vegetation-state','status':'candidate','sources':['https://gerslab.cahnr.uconn.edu/wp-content/uploads/sites/2514/2021/06/ZheZhu_CCDC.pdf']},{'type':'REQUIRES_VALIDATION','target':'validation:forest-evidence','status':'candidate','sources':['https://doi.org/10.1080/01621459.1993.10476408']}],'''A proposed median/MAD anomaly rule with a minimum effect size and missing-data guards. Literature supports robust scale and temporal QA concepts, not these NDVI cutoffs. All k/noise-floor/effect/min-count choices require validation. Applicable only to calibrated, quality-masked comparable references; no road label, probability or legal inference follows. Review questions: reference sampling bias, small-sample uncertainty, seasonal alignment and independent holdout design. Contradictions: no external labels; baseline/method valid support differs. Run results remain threshold_experiments.json and persistence_experiment.json in review evidence, not graph facts. Geography/time scope: method proposal generic; execution evidence limited to this Estonia AOI and 2025/2026 summer scenes.'''),('validation:linear-feature-identity','validation','Dated independent linear-feature identity assessment','knowledge/validation/validation-linear-feature-identity.md',['https://www.mdpi.com/2072-4292/8/6/488','https://geoportaal.maaruum.ee/eng/spatial-data/orthophotos/download-orthophotos-p662.html'],[{'type':'REQUIRES_OBSERVATION','target':'observation:optical-vegetation-state','status':'candidate','sources':['https://www.mdpi.com/2072-4292/8/6/488']}],'''Adjacent validation question for forest-disturbance interpretation: establish physical line identity using sufficiently resolved, dated, unobscured independent before/after imagery, spatial alignment and official records. Separate road existence, construction, reopening/widening, prior forest and legal attribution. Missing maps/masks are weak negative evidence. Conflicting acquisition metadata prevents interval inference. Geometry/width and source independence must be evaluated explicitly. Contradictions and limitations: the current imagery has date conflicts, no independent after pair, and railway/forestry-track alternatives. Intended as a human-review candidate; local ROI claims remain evidence rather than canonical concepts.''')]
# REQUIRES_OBSERVATION cannot originate from validation under current ontology; avoid proposing invalid edges.
proposals[1]=(*proposals[1][:5],[],proposals[1][6])
for id,typ,title,target,sources_,relations,body in proposals:
 meta={'id':id,'type':typ,'title':title,'version':'0.1','status':'candidate','updated':'2026-10-06','review_after':'2027-04-06','sources':sources_,'relations':relations};jsonschema.validate(meta,schema);assert id not in {n['id'] for n in json.loads((LAB/'graph/generated/knowledge.json').read_text())['nodes']}
 file=id.replace(':','-')+'.md';(K/file).write_text('---\n'+yaml.safe_dump(meta,sort_keys=False)+'---\n\n'+body+'\n');index.append({'id':id,'registered':False,'status':'candidate','path':file,'intended_canonical_target':target,'schema_check':'passed','supporting_evidence':['L04','L08'] if typ=='method' else ['L01','independent_map_evidence.json'],'contradicting_or_limiting_evidence':['No independent labels','Conflicting orthophoto dates'],'promotion':'human scientific review required; no canonical edits'})
write_json(K/'index.json',index)
# Claim status and evidence handoff.
claims=[]
for roi in ('ROI-01','ROI-02'):
 for key,prop in [('linear_change','A changed linear optical pattern is visible in the sampled corridor.'),('road_identity','The entire changed linear feature is a road.'),('new_construction','The sampled feature is a road entirely absent on 15 June 2025 and newly constructed by 20 June 2026.'),('appearance_interval','A road appearance interval can be bounded from sufficiently dated before/after evidence.'),('prior_forest','The affected area met an approved forest definition before change.'),('legal_attribution','The disturbance establishes legal deforestation or identifies lawful/unlawful activity.')]:
  status='unresolved';reason='Evidence does not resolve the proposition.';support=[];refute=[]
  if key=='linear_change':status='supported';reason='Sensor-derived before/after imagery and optical candidates support a changed linear pattern provisionally, with manual geometry and confounder uncertainty.';support=['E-RGB','E-ROI']
  if key=='new_construction' and roi=='ROI-02':status='rejected';reason='For the sampled main carriageway, the reference RGB already shows a road-like alignment; aerial imagery supports a paved road. This does not reject new branches, widening or work elsewhere.';refute=['E-RGB','ROI-02-2025']
  if key=='road_identity':reason='ROI-02 has a paved road at its sampled point, but that does not label the entire changed feature; ROI-01 retains rail/earthworks/track alternatives.'
  if key in ('prior_forest','legal_attribution'):status='not_tested';reason='No approved dated forest baseline or legal/permit evidence supplied or acquired.'
  claims.append({'id':roi+'-'+key,'roi_id':roi,'proposition':prop,'status':status,'supporting_evidence_ids':support,'refuting_evidence_ids':refute,'rationale':reason,'semantic_concepts':['claim:monthly-non-truth','validation:forest-evidence']})
limitations=['Manually chosen candidates are not uniquely identified by the user; exact surveyed line/width remains uncertain.','Sampling buffers are approximate: 40 m tolerance is not measured registration error.','Two optical local integer-shift checks found zero best shift; SAR/subpixel registration remains unverified.','Reference optical variability comes from a selected eight-date sample; some pixels have fewer than five clear dates.','Persistence covers two 500 m windows on 7, 20 and 30 June only, not full corridors/monthly confirmation.','Independent imagery is WMS-derived with conflicting date metadata; no verified before/after interval.','13 current original-run artifacts mismatch archived output hashes; unchanged during review and current hashes pinned.','No held-out road labels: all threshold results are screening stability, not accuracy.','BFAST, CCDC, probabilistic fusion, NDMI/NBR and causal/legal attribution not executed; appropriate data or labels absent.','Interactive browser rendering unavailable; maps/figures inspected through image tools and links checked.']
evidence=[{'id':'E-RGB','path':'roi_locator.png','identity':'Original matched RGB and paired native20m crops','observation_date':['2025-06-15','2026-06-20'],'processing':'provider-calibrated RGB; fixed 0–.3 stretch/gamma2.2','independence_group':'Sentinel-2-EarthSearch','accessibility':'readable','limitations':['Not independent road labels; display/source resolution differs.']},{'id':'E-ROI','path':'roi_metrics.json','identity':'Tiled signal/mask audit','observation_date':None,'processing':'continuous optical and summer SAR summaries','independence_group':'derived-Sentinel-evidence','accessibility':'executed','limitations':['Provisional buffers.']},{'id':'E-ROBUST','path':'threshold_experiments.json','identity':'18-setting supplied MAD heuristic','observation_date':None,'processing':'calibrated tiled per-scene NDVI reference','independence_group':'derived-Sentinel-evidence','accessibility':'executed','limitations':['Unvalidated thresholds.']},{'id':'E-PERSIST','path':'persistence_experiment.json','identity':'Three-date 500m persistence experiment','observation_date':['2026-06-07','2026-06-20','2026-06-30'],'processing':'>=2 detections on >=3 valid dates','independence_group':'Sentinel-2-EarthSearch','accessibility':'executed','limitations':['Local windows; not monthly truth.']}]
evidence+=ind['records']
write_json(R/'findings.json',{'schema_version':'1.0','claims':claims,'limitations':limitations,'summary':'Changed linear patterns are supported provisionally; a newly constructed road is not established. The sampled ROI-02 main carriageway is already visible at reference date.','metrics':audit,'robust_shared_support':shared,'source_access_limits':load('literature_evidence.json'),'stage_status':{'inspect':'complete within declared sampling limits','research':'partial: some original full texts inaccessible','corroborate':'partial: date conflict and no verified high-resolution after pair','report':'complete; unresolved propositions preserved'}})
artifacts={str(p.relative_to(R)):checksum(p) for p in R.rglob('*') if p.is_file() and p.suffix not in ('.pyc',) and p.name not in ('investigation.json','artifact_manifest.json')}
write_json(R/'investigation.json',{'schema_version':'1.0','investigation_id':R.name,'updated_at_utc':now,'paths':{'REPO':str(REPO),'LAB':str(LAB),'RUN':str(RUN),'REVIEW':str(R)},'repo_shas':{'repo':sem['repo_commit'],'lab':sem['lab_commit']},'worktree_states':{'repo':subprocess.check_output(['git','status','--porcelain'],text=True),'lab':sem['lab_worktree']},'run_manifest_sha256':checksum(RUN/'run_manifest.json'),'rois':rois,'claims':claims,'sources':evidence,'artifacts':artifacts,'limitations':limitations,'stages':{'inspect':{'status':'complete','scope':'declared manual candidates, tiled experiments, local persistence'},'research':{'status':'partial','reason':'some full-text sources inaccessible; 9 scoped records'},'corroborate':{'status':'partial','reason':'no adequately dated independent before/after pair'},'report':{'status':'complete','reason':'evidence and missing work audited, no promotion'}}})
# Report includes observed numbers and explicit propositions, not earlier obsolete blockers.
def table(headers,rows):return '| '+' | '.join(headers)+' |\n| '+' | '.join(['---']*len(headers))+' |\n'+''.join('| '+' | '.join(map(str,row))+' |\n' for row in rows)
text='''# Sentinel linear-feature review

A newly constructed road is not established. The two sampled candidates show optical linear-change patterns, but their interpretation remains conditional. ROI-02’s sampled main road was already visible in the 15 June 2025 reference; new branches, widening or surrounding clearing are separate unresolved claims. ROI-01 retains forestry-track, railway/earthworks and road hypotheses. No prior-forest or legal-deforestation conclusion is justified.

'''
text+=table(['Claim','ROI-01','ROI-02'],[(k,next(c['status'] for c in claims if c['id']=='ROI-01-'+k),next(c['status'] for c in claims if c['id']=='ROI-02-'+k)) for k in ('linear_change','road_identity','new_construction','appearance_interval','prior_forest','legal_attribution')])
text+='''
## Sensor evidence and denominators

Run: aoi-s2-s1-jja-2025-2026-sigma; AOI: example-aoi in Estonia. Purpose: v2-style provisional disturbance screening plus an adjacent linear-feature review, not validated monthly forest monitoring. Area: determinant of 20 m EPSG:6933 equal-area grid, 0.04 hectares/pixel. No forest gate. These are all-land-cover candidate hectares.

'''+table(['Variant','Candidates','Hectares','Valid pixels'],[(k,v['anomaly_pixels'],v['anomaly_ha'],v['valid_pixels']) for k,v in audit['counts'].items()])
text+='\n'+table(['Pair','Both positive','Optical-only','Radar-only','Neither','Joint valid','Unavailable grid pixels'],[(k,*[v[t] for t in ('agreement','optical_only','radar_only','neither','joint_valid','unavailable')]) for k,v in audit['comparison'].items()])
text+='''
Fixed and sigma must each be compared with their own SAR variant. The fixed optical reference is one 15 June 2025 acquisition; sigma uses a mean/std of eight selected 2025 summer dates. Target optical is 20 June 2026. Radar is twelve selected dates per summer, ascending orbit 160, linear power converted to dB before median composition. The strict radar gate is ΔVV < −1.5 dB AND ΔVH < −1 dB. The combined mask is paired-valid optical AND radar; zero optical-valid/radar-unavailable pixels explains that all removed optical candidates fail thresholds. Missing pixels are never filled with zero. Narrower masks do not demonstrate greater accuracy or physical road absence.

Fixed retains 9,469/91,291 optical candidates (10.37%); sigma retains 12,875/121,242 (10.62%). The displayed reference RGB is not the eight-date sigma/robust composite. Calibration uses archived gain=.0001 and no second BOA offset for flagged COGs; the provider interpretation is documented, not independently radiometrically validated. SCL 4/5/6/7 is accepted, with nearest quality and bilinear continuous resampling. No spatial SAR speckle filter is applied; temporal median is declared. Summer SAR and June optical cannot establish the same event date.

## Candidate-region signals

ROIs are provisional manually traced sampling corridors with 40 m buffers, plus two visually stable forest controls. They are not surveyed road footprints. Projected centreline length and rough apparent widths are recorded in rois.geojson. Width approximately 20–60 m is a visual estimate (1–3 analysis pixels); source-pixel equivalents do not constitute native-resolution measurement. Alignment checks at two optical patches preferred zero integer shift (correlations .942 and .786); no correction was made. This does not certify SAR or subpixel registration.

'''+table(['Region','Joint-valid pixels','Sigma','Sigma+SAR','VV-only failure','VH-only failure','Both failures','Median ΔVV dB','Median ΔVH dB'],[(r['roi_id'],r['valid'],r['sigma'],r['sigma_and'],r['vv_only_fail'],r['vh_only_fail'],r['both_fail'],round(r['vv_change_median'],3),round(r['vh_change_median'],3)) for r in metrics])
text+='''
In ROI-01, 730 sigma candidates fail SAR: 395 fail VV alone, four VH alone and 331 both. In ROI-02, 195 fail: 138 VV alone and 57 both. These are sampled buffers, not full-feature completeness estimates. ROI-level continuous percentiles and rejected-pixel distributions are in roi_metrics.csv and common_support_and_roi_robust.json. Surrounding vegetation and manual-trace uncertainty dilute corridor statistics. Two visual controls have zero optical candidates but a few radar candidates, demonstrating disagreement without proving any accuracy rate.

Possible mechanisms include mixed pixels, moisture/roughness maintaining backscatter, temporal median dilution, seasonal agriculture/phenology, clouds/SCL edges, surface works and registration errors. Literature supports these as alternatives; local cause was not measured. Official Rail Baltic reports describe regional rail and access-road works, but no exact geospatial association was proved. See literature_review.md and corroboration.md.

## Executed threshold and persistence experiments

The supplied robust helper passed five synthetic checks (missing samples, minimum count, zero MAD/noise floor, strict boundaries, shape mismatch). Tile-level calibrated reference mean/std reproduced the archived rasters within 2e−6 on finite support. The experiment uses median m, MAD, score z=(m−target)/max(1.4826 MAD, epsilon); candidates require at least five clear unique reference dates, z>k and m−target>delta_min. Invalid NDVI and missing targets remain unavailable. k={2,2.5,3}, delta_min={.1,.15,.2}, epsilon={.02,.05}: all 18 settings retained, four masks each (optical, AND, OR, discordance), three portable maps each.

Default (2.5,.15,.02): 61,610 optical candidates (2,464.40 ha), 7,582 AND (303.28 ha), 150,257 OR (6,010.28 ha), on 2,735,752 paired-valid pixels. Across all settings optical counts range 45,860–89,317 and AND 5,865–10,217. The default intersection with fixed/sigma support has 2,735,727 valid pixels: fixed=77,092, fixed+SAR=7,812, sigma=92,146, sigma+SAR=9,312, robust=61,610, robust+SAR=7,582. Compare on that intersection rather than treating area differences caused by missing references as improvement.

Three-date persistence was executed in two 500 m windows using 7, 20 and 30 June 2026, at least ten-day separation, AOI-clear ranking and pixel SCL masking. ROI-01: 145 pixels valid on all dates, two recurring detections; ROI-02: 676 valid, 149 recurring detections. Counts/masks and access/calibration evidence are preserved under experiments/persistence/ and cache/persistence/. These are repeated optical anomalies, not independent observations of road identity, full-corridor persistence, the Lab’s consecutive-month confirmation or BFAST/CCDC. No held-out labels, probabilistic fusion, accuracy statistics or calibrated probabilities are claimed.

## Independent imagery and dating

Official historical WMS capabilities and small windows were downloaded. Requested sampling is .5 m; native source resolution remains unverified. 2023/2024 responses contained attribution but no imagery. The 2025 layer shows a paved road and vehicles at ROI-02, and forest clearings/tracks at ROI-01. Generic metainfo says flight 9 June 2023/GSD25 despite the 2025 layer: this contradiction remains unresolved. Neither date is silently assigned to the pixels. Source sheet listing attempts through the web tool failed. No adequately dated independent before/after pair or verified 2026 high-resolution after image was obtained. Appearance interval, widening/reopening and construction identity therefore remain unresolved. The photographs are not a legal forest definition; no baseline or permit evidence was supplied.

## Provenance, tests and review candidates

Graph and downstream-descriptor checks passed without writing: 68 concepts, 72 validated and 67 candidate relations; revision ef90b703ae150c09cc7cac6fd324d7b5ecd8305a5a0d5130ec0deb61ed291e49. Run semantic-provenance validation passed. Full revisions/worktree states, concept versions/status, relationships and contextual corpus hashes are in semantic_trace.json. New experiment helper/code hashes and package versions are in skill_installation.json, artifact_manifest.json and environment.json. No linked concept was past its review-after deadline on 6 October 2026. Validated contract transcriptions/API capabilities do not empirically validate threshold choices; the NDVI method and workflow registrations remain candidates. This is the Lab’s OKF-oriented profile, not asserted full-standard conformance.

13 current run files mismatch the original manifest’s output hashes (manifest_verification.json). The presentation update does not provide replacement hashes for all of them. This was pre-existing: every original/source-run file matched this review’s before/after checksums. Current hashes are pinned, and baseline counts/AND logic independently reproduced. The discrepancy remains a reproducibility limitation; originals were not repaired.

'''
text+='Repository SHA: '+sem['repo_commit']+'; Lab SHA: '+sem['lab_commit']+'.\n\n'
text+='''Source-grounded candidates are in knowledge_candidates/index.json with schema-checked Markdown records. Proposed IDs are unregistered; all relations remain candidate. Human review, evidence, tests and drift review are required before any canonical promotion. No corpus/generated graph was edited.

The four installed skills and SHA-256 checks are recorded in skill_installation.json. All 36 repository tests passed (repository_tests.log); self-test, graph/descriptor/provenance checks, mask counts, same-grid assertions, original integrity and HTML link checks are archived. Browser rendering was unavailable; raw/derived PNG figures and all threshold overview variants were inspected with image tools.

Reproduction from repository root:

```
.venv/bin/python reviews/20261006T174722Z-sentinel-road-investigation/audit.py
.venv/bin/python reviews/20261006T174722Z-sentinel-road-investigation/experiment.py
.venv/bin/python reviews/20261006T174722Z-sentinel-road-investigation/persistence.py
.venv/bin/python reviews/20261006T174722Z-sentinel-road-investigation/verify_and_figures.py
.venv/bin/python reviews/20261006T174722Z-sentinel-road-investigation/add_metrics.py
.venv/bin/python reviews/20261006T174722Z-sentinel-road-investigation/finish_review.py
```

Run fetch_orthophotos.py only to refresh external queries; response identity may change. Raster experiments reuse cached/calibrated provider windows, tiled IO, pure repository feature/fusion and reporting functions. All review/cache/artifact paths are recorded in investigation.json and artifact_manifest.json. No Earth Engine dependency or canonical update is needed. No generated large raster was committed.

Remaining evidence needed: user-confirmed precise feature or surveyed centreline; independently dated native-resolution before/after imagery; road versus rail/track alignment and construction records; a separately approved prior-forest baseline; and any relevant legal documents. Additional methods requiring multi-year seasonal series or independent holdouts remain proposals.

Hansen annual loss is not monthly ground truth. Monthly outputs in this report are derived from Sentinel composites and (where applicable) trained under annual weak supervision. They have not been validated as month-resolved truth.

'''
# Preserve complete original contractual blocks as review-only provenance.
manifest=json.loads((RUN/'run_manifest.json').read_text());blocks={k:manifest[k] for k in ('data_provenance','forest_definition','area_method','limitations','semantic_provenance')};write_json(R/'original_contract_blocks.json',blocks)
text+='Complete original data-source, forest-definition, area-method, limitations and semantic-provenance blocks: original_contract_blocks.json. Literature links and access levels: literature_review.md / references.bib.\n'
(R/'report.md').write_text(text)
(R/'visual_findings.md').write_text(text.split('## Executed threshold')[0]+'\nQuestions for corroboration: precise road/rail identity, dated independent before/after, reopening/widening, prior forest and legal evidence.\n')
# Render Markdown with a small deterministic converter, no external runtime.
lines=text.splitlines();parts=[];in_code=False;in_list=False;i=0
while i<len(lines):
 line=lines[i]
 if line.startswith('```'):
  if in_code:parts.append('</code></pre>');in_code=False
  else:parts.append('<pre><code>');in_code=True
 elif in_code:parts.append(html.escape(line)+'\n')
 elif line.startswith('|'):
  rows=[]
  while i<len(lines) and lines[i].startswith('|'):
   vals=[html.escape(x.strip()) for x in lines[i].strip('|').split('|')]
   if not all(x.strip('-: ') == '' for x in vals):rows.append(vals)
   i+=1
  parts.append('<table><thead><tr>'+''.join('<th>'+x+'</th>' for x in rows[0])+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+x+'</td>' for x in row)+'</tr>' for row in rows[1:])+'</tbody></table>');continue
 elif line.startswith('#'):n=len(line)-len(line.lstrip('#'));parts.append(f'<h{n}>'+html.escape(line[n:].strip())+f'</h{n}>')
 elif line.strip():parts.append('<p>'+html.escape(line)+'</p>')
 i+=1
figure='<h2>Figures and maps</h2><p>Identical RGB footprint/stretch; date labels distinguish imagery from composites. Approximate ROI buffers are sampling regions, not road boundaries.</p><img src="roi_locator.png" alt="Candidate regions"><img src="contact_sheet.png" alt="Four baseline maps">'
for roi in ('ROI-01','ROI-02'):
 figure+=f'<h3>{roi}: 15 June 2025 left, 20 June 2026 right; native 20 m analysis-grid RGB</h3><div class="pair"><img src="{roi}-reference-native.png"><img src="{roi}-target-native.png"></div>'
figure+='<h3>Continuous pixel distributions and threshold sensitivity</h3><img src="continuous_signal_summary.png"><img src="threshold_sensitivity.png"><h3>All 18 robust settings, optical/AND/OR overview</h3><img src="robust_contact_sheet.png"><h3>Default robust optical / AND / OR</h3><div class="triple">'+''.join(f'<img src="robust-default-{m}.png" alt="{m}">' for m in ('optical','and','or'))+'</div><h3>Official 2025-layer aerial windows; exact acquisition date unresolved</h3><div class="pair"><img src="cache/orthophotos/ROI-01-2025.png"><img src="cache/orthophotos/ROI-02-2025.png"></div>'
links=['maps/comparison.html','threshold_experiments.json','sigma_sar_sensitivity.json','common_support_and_roi_robust.json','roi_metrics.csv','persistence_experiment.json','independent_map_evidence.json','literature_review.md','references.bib','semantic_trace.json','original_contract_blocks.json','manifest_verification.json','original_integrity.json','investigation.json','knowledge_candidates/index.json','skill_installation.json']
figure+='<h2>Evidence artifacts</h2><ul>'+''.join(f'<li><a href="{p}">{p}</a></li>' for p in links)+'</ul><h3>Every experimental setting</h3><ul>'
for r in exp['settings']:
 folder=str(Path(r['artifacts']['optical.tif']['path']).parent)
 figure+='<li>'+f"k={r['k']}, drop={r['delta_min']}, floor={r['epsilon']}: "+' '.join(f'<a href="{folder}/maps_{m}/map.html">{m}</a>' for m in ('optical','and','or'))+'</li>'
figure+='</ul>'
(R/'report.html').write_text('<!doctype html><html><head><meta charset="utf-8"><title>Sentinel linear feature evidence review</title><style>body{font:16px/1.5 sans-serif;max-width:1200px;margin:32px auto;padding:0 20px}table{border-collapse:collapse;font-size:14px;width:100%}th,td{padding:7px;border:1px solid #ccc;text-align:left}img{max-width:100%}.pair,.triple{display:flex;align-items:flex-start;gap:1%}.pair img{width:49%}.triple img{width:32%}pre{background:#eee;padding:12px;overflow:auto}h2{margin-top:36px}</style></head><body>'+''.join(parts)+figure+'</body></html>')
# Local link/image audit, portable map validation, final evidence checksum inventory.
failures=[]
for p in [R/'report.html',*R.glob('experiments/*/maps_*/map.html')]:
 for ref in re.findall(r'(?:src|href)="([^"]+)"',p.read_text()):
  if not ref.startswith(('http:','https:','data:','#')) and not (p.parent/ref).exists():failures.append({'file':str(p.relative_to(R)),'reference':ref})
write_json(R/'html_link_audit.json',{'checked_html':55,'missing':failures,'browser_rendering':'unavailable; image QA performed'})
assert not failures,failures
before=load('original_hashes_before.json');changed=[p for p,h in before.items() if checksum(p)!=h];write_json(R/'original_integrity.json',{'files_checked':len(before),'unchanged':not changed,'changed':changed});assert not changed
write_json(R/'artifact_manifest.json',{'created_at':now,'artifacts':{str(p.relative_to(R)):checksum(p) for p in R.rglob('*') if p.is_file() and p.name!='artifact_manifest.json' and p.suffix!='.pyc'}})
print('Final evidence report generated, candidates schema-checked, links audited, originals unchanged.')
